"""Tests for the dashboard translation catalog."""

import pytest

from payment_dashboard.i18n import (
    DEFAULT_LANGUAGE,
    SUPPORTED_LANGUAGES,
    TRANSLATIONS,
    translate,
)

PLAYFUL_KEYS = {
    "hero.eyebrow",
    "hero.title",
    "hero.subtitle",
    "hero.database_live",
    "hero.demo_mode",
    "actions.reset_filters",
    "empty.title",
    "empty.body",
    "ai.title",
    "ai.description",
    "ai.generate",
    "ai.generating",
    "ai.summary",
    "ai.risks",
    "ai.actions",
    "ai.evidence",
    "ai.origin.ai",
    "ai.origin.local",
    "ai.requires_data",
    "ai.invalid_response",
    "database.fallback_not_configured",
    "database.fallback_unavailable",
    "source.live_label",
    "source.demo_label",
    "source.simulation_disclosure",
    "source.degraded_warning",
    "source.diagnostics",
    "source.diagnostic_category",
    "source.retry_guidance",
    "source.retry",
    "pagination.page",
    "pagination.previous",
    "pagination.next",
    "pagination.summary",
}

SHELL_KEYS = {
    "shell.product_name",
    "shell.navigation",
    "shell.view.overview",
    "shell.view.gateways",
    "shell.view.routing",
    "shell.view.transactions",
    "shell.view.admin",
    "shell.reset_filters",
    "shell.view_description.overview",
    "shell.view_description.gateways",
    "shell.view_description.routing",
    "shell.view_description.transactions",
    "shell.view_description.admin",
}


def test_translation_catalogs_have_matching_keys() -> None:
    assert set(TRANSLATIONS["en"]) == set(TRANSLATIONS["my"])


def test_playful_dashboard_copy_exists_in_both_languages() -> None:
    for language in ("en", "my"):
        assert all(TRANSLATIONS[language][key].strip() for key in PLAYFUL_KEYS)


def test_command_center_shell_copy_exists_in_both_languages() -> None:
    """The navigation shell must remain fully bilingual as views are added."""
    for language in ("en", "my"):
        assert all(TRANSLATIONS[language][key].strip() for key in SHELL_KEYS)


def test_command_center_destinations_use_the_exact_english_vocabulary() -> None:
    """Navigation labels must match the approved command-center destinations."""
    assert translate("shell.view.gateways") == "Gateways"
    assert translate("shell.view.routing") == "Routing Lab"
    assert translate("shell.view.admin") == "Admin"


def test_simulation_disclosure_is_truthful_in_both_languages() -> None:
    english = translate("source.simulation_disclosure", "en", version="controlled-v1")
    myanmar = translate("source.simulation_disclosure", "my", version="controlled-v1")

    assert "controlled-v1" in english
    assert "gateway assignments and dashboard outcomes are synthetic" in english
    assert "controlled-v1" in myanmar
    assert "Gateway" in myanmar and "အတု" in myanmar


def test_english_is_default_and_burmese_is_supported() -> None:
    assert DEFAULT_LANGUAGE == "en"
    assert SUPPORTED_LANGUAGES == ("en", "my")
    assert translate("dashboard.title") == "Payment Success Monitor"
    assert translate("dashboard.title", "my") == "ငွေပေးချေမှု အောင်မြင်နှုန်း စောင့်ကြည့်စနစ်"


def test_unknown_language_and_blank_translation_fall_back_to_english() -> None:
    assert translate("dashboard.title", "fr") == "Payment Success Monitor"
    assert translate("test.fallback", "my") == "Fallback"


def test_load_error_and_recovery_guidance_are_translated() -> None:
    assert (
        translate("errors.load_data", exc="missing gateway data")
        == "Unable to load dashboard data: missing gateway data"
    )
    assert translate("errors.load_data", "my", exc="gateway data မရှိပါ") == (
        "Dashboard data ကို မဖွင့်နိုင်ပါ: gateway data မရှိပါ"
    )
    assert translate("errors.prepare_data_guidance", "my") == (
        "`python -m payment_dashboard.prepare_data` ဖြင့် ပြင်ဆင်ထားသော dataset ကို "
        "ဖန်တီးပြီး ဤစာမျက်နှာကို ပြန်လည်ဖွင့်ပါ။"
    )


def test_degraded_warning_and_retry_are_bilingual() -> None:
    assert "Simulated demo data is active" in translate("source.degraded_warning")
    assert "သရုပ်ပြဖန်တီးထားသော ဒေတာ" in translate("source.degraded_warning", "my")
    assert translate("source.retry") == "Retry MongoDB"
    assert translate("source.retry", "my") == "MongoDB ကို ထပ်မံကြိုးစားရန်"


def test_burmese_gateway_success_chart_label_matches_the_ui_contract() -> None:
    assert translate("charts.success_rate_by_gateway", "my") == ("ဂိတ်ဝေးအလိုက် အောင်မြင်နှုန်း")


def test_language_control_copy_is_bilingual() -> None:
    assert translate("language.control_label", "en") == "Language / ဘာသာစကား"
    assert translate("language.control_label", "my") == "Language / ဘာသာစကား"
    assert translate("language.current", "en", name="English") == "Current: English"
    assert translate("language.current", "my", name="မြန်မာ") == "လက်ရှိ: မြန်မာ"


def test_ai_brief_origin_labels_are_bilingual() -> None:
    assert translate("ai.origin.ai") == "Generated by AI"
    assert translate("ai.origin.local") == "Generated locally (AI unavailable)"
    assert translate("ai.origin.ai", "my") == "AI ဖြင့် ဖန်တီးထားသည်"
    assert translate("ai.origin.local", "my") == ("စက်တွင်း၌ ဖန်တီးထားသည် (AI မရရှိနိုင်ပါ)")


def test_gateway_table_header_is_translated() -> None:
    assert translate("table.gateway") == "Gateway"
    assert translate("table.gateway", "my") == "ဂိတ်ဝေး"


@pytest.mark.parametrize(
    ("key", "english", "burmese"),
    [
        ("table.transaction_id", "Transaction ID", "ငွေပေးချေမှု ID"),
        ("table.timestamp", "Timestamp", "အချိန်မှတ်တမ်း"),
        (
            "table.transaction_type",
            "Transaction Type",
            "ငွေပေးချေမှု အမျိုးအစား",
        ),
        (
            "table.transaction_status",
            "Transaction Status",
            "ငွေပေးချေမှု အခြေအနေ",
        ),
        ("table.transaction_amount", "Transaction Amount", "ငွေပမာဏ"),
        ("table.device_used", "Device Used", "အသုံးပြုသည့် စက်"),
        ("table.latency_ms", "Latency (ms)", "တုံ့ပြန်ချိန် (ms)"),
        ("table.fraud_flag", "Fraud Flag", "လိမ်လည်မှု အမှတ်အသား"),
    ],
)
def test_recent_transaction_table_headers_are_translated(
    key: str,
    english: str,
    burmese: str,
) -> None:
    assert translate(key) == english
    assert translate(key, "my") == burmese


def test_admin_labels_exist_in_both_languages() -> None:
    for language in ("en", "my"):
        assert translate("admin.title", language) != "admin.title"
        assert translate("admin.login", language) != "admin.login"
        assert translate("admin.fallback_disabled", language) != (
            "admin.fallback_disabled"
        )
