"""Translation catalog and lookup helpers for the payment dashboard."""

from typing import Final, Literal

Language = Literal["en", "my"]

DEFAULT_LANGUAGE: Final[Language] = "en"
SUPPORTED_LANGUAGES: Final[tuple[Language, ...]] = ("en", "my")

TRANSLATIONS: Final[dict[str, dict[str, str]]] = {
    "en": {
        "language.label": "Language",
        "language.english": "English",
        "language.burmese": "မြန်မာ",
        "language.control_label": "Language / ဘာသာစကား",
        "language.current": "Current: {name}",
        "dashboard.title": "Payment Success Monitor",
        "dashboard.description": (
            "Track transaction health, compare simulated gateways, and investigate "
            "payment failures from one local dashboard."
        ),
        "dashboard.disclaimer": (
            "Academic demo · Gateway assignments and payment outcomes are "
            "controlled synthetic data, not real bank or gateway performance."
        ),
        "shell.product_name": "Payment Command Center",
        "shell.navigation": "Command center navigation",
        "shell.view.overview": "Overview",
        "shell.view.gateways": "Gateways",
        "shell.view.routing": "Routing Lab",
        "shell.view.transactions": "Transactions",
        "shell.view.admin": "Admin",
        "shell.reset_filters": "Reset filters",
        "shell.view_description.overview": "Live payment health at a glance.",
        "shell.view_description.gateways": "Compare gateway performance and alerts.",
        "shell.view_description.routing": "Optimize payment routing decisions.",
        "shell.view_description.transactions": "Inspect filtered payment activity.",
        "shell.view_description.admin": "Manage dashboard access and payments.",
        "sidebar.controls": "Dashboard controls",
        "sidebar.replay_description": (
            "Browse chronological history, then narrow the visible analysis."
        ),
        "sidebar.replayed_transactions": "History transactions",
        "sidebar.replay_help": (
            "Controls the historical sample used by the legacy CSV view."
        ),
        "sidebar.replay_count": "{replay_count:,} of {total_count:,} transactions",
        "sidebar.display_filters": "Display filters",
        "sidebar.gateway": "Gateway",
        "sidebar.all_gateways": "All gateways",
        "sidebar.transaction_type": "Transaction type",
        "sidebar.all_transaction_types": "All transaction types",
        "sidebar.device": "Device",
        "sidebar.all_devices": "All devices",
        "sidebar.status": "Status",
        "sidebar.all_statuses": "All statuses",
        "sidebar.date_range": "Date range",
        "sidebar.filter_note": (
            "Filters change the charts and KPIs. Alert calculations always use "
            "the full active transaction history."
        ),
        "kpi.transactions": "Transactions",
        "kpi.success_rate": "Success rate",
        "kpi.failed": "Failed",
        "kpi.average_latency": "Average latency",
        "kpi.active_alerts": "Active alerts",
        "hero.eyebrow": "Payment pulse",
        "hero.title": "{successful:,} payments made it through ✦",
        "hero.subtitle": (
            "{success_rate:.1%} success rate · {average_latency_ms:.1f} ms "
            "average latency"
        ),
        "hero.database_live": "Live MongoDB data",
        "hero.demo_mode": "Demo data",
        "actions.reset_filters": "Reset filters",
        "empty.title": "No matching payments",
        "empty.body": "Try resetting one or more filters to see transactions.",
        "ai.title": "AI operations brief",
        "ai.description": (
            "Generate a concise summary with MiMo 2.5 Pro. Only aggregate "
            "dashboard metrics are shared."
        ),
        "ai.generate": "Generate AI brief",
        "ai.generating": "Generating AI brief...",
        "ai.summary": "Summary",
        "ai.risks": "Risks",
        "ai.actions": "Actions",
        "ai.evidence": "Evidence",
        "ai.origin.ai": "Generated by AI",
        "ai.origin.local": "Generated locally (AI unavailable)",
        "ai.requires_data": (
            "Select filters that return transactions before generating a brief."
        ),
        "ai.invalid_response": (
            "The AI brief could not be generated. Please try again."
        ),
        "database.fallback_not_configured": (
            "The database is not configured, so demo data is being shown."
        ),
        "database.fallback_unavailable": (
            "The database is temporarily unavailable, so demo data is being shown."
        ),
        "source.live_label": "Live MongoDB data",
        "source.demo_label": "Simulated demo data",
        "source.simulation_disclosure": (
            "Simulation {version}: gateway assignments and dashboard outcomes "
            "are synthetic and controlled for this academic demo."
        ),
        "source.degraded_warning": (
            "MongoDB is unavailable. Simulated demo data is active; editing is "
            "disabled."
        ),
        "source.diagnostics": "Database status and recovery",
        "source.diagnostic_category": "Diagnostic category: {category}",
        "source.retry_guidance": (
            "Check the MongoDB configuration or connection, then retry."
        ),
        "source.retry": "Retry MongoDB",
        "pagination.page": "Transaction page",
        "pagination.previous": "Previous page",
        "pagination.next": "Next page",
        "pagination.summary": "Page {page} of {pages} · {total:,} transactions",
        "health.title": "Gateway health",
        "health.description": (
            "An alert triggers when a gateway's latest 50 transactions fall at "
            "least 10 percentage points below its full-data baseline."
        ),
        "health.no_alert": "No gateway currently exceeds the 10-point alert threshold.",
        "health.action_required": (
            "Action required: success-rate degradation detected for {names}."
        ),
        "health.insufficient_history": "Insufficient history",
        "health.alert": "Alert",
        "health.healthy": "Healthy",
        "health.baseline": "Baseline",
        "health.latest_50": "Latest 50",
        "health.drop": "Drop",
        "health.samples": "Samples (baseline/recent)",
        "health.periods": "Compared periods (UTC)",
        "health.interval": "95% drop interval",
        "charts.gateway_performance": "Gateway performance",
        "charts.success_rate_by_gateway": "Success rate by gateway",
        "charts.transaction_volume_by_gateway": "Transaction volume by gateway",
        "charts.success_trend": "Success trend",
        "charts.failures_by": "Failures by {title}",
        "dimensions.gateway": "Gateway",
        "dimensions.timestamp": "Timestamp",
        "dimensions.fraud_flag": "Fraud flag",
        "dimensions.latency_band": "Latency band",
        "dimensions.device": "Device",
        "dimensions.transaction_type": "Transaction type",
        "sections.failure_analysis": "Failure analysis",
        "sections.failure_analysis_description": (
            "Break down failed transactions to identify recurring patterns."
        ),
        "table.gateway": "Gateway",
        "table.transaction_id": "Transaction ID",
        "table.timestamp": "Timestamp",
        "table.transaction_type": "Transaction Type",
        "table.transaction_status": "Transaction Status",
        "table.transaction_amount": "Transaction Amount",
        "table.device_used": "Device Used",
        "table.latency_ms": "Latency (ms)",
        "table.fraud_flag": "Fraud Flag",
        "table.recent_transactions": "Recent transactions",
        "guide.title": "How to interpret this dashboard",
        "guide.content": (
            "- **Baseline** is each gateway's success rate across active history "
            "strictly before the latest-50 window.\n"
            "- **Latest 50** is the gateway's success rate in its newest 50 active "
            "transactions.\n"
            "- **Drop** is baseline minus latest-50 performance.\n"
            "- Gateway assignment and outcomes are controlled synthetic values, so "
            "comparisons are for demonstration only."
        ),
        "errors.no_matching_transactions": (
            "No transactions match the selected filters. Clear one or more "
            "sidebar filters to continue."
        ),
        "errors.load_data": "Unable to load dashboard data: {exc}",
        "errors.prepare_data_guidance": (
            "Generate the prepared dataset with "
            "`python -m payment_dashboard.prepare_data` and refresh this page."
        ),
        "optimization.eyebrow": "SYNTHETIC BENCHMARK",
        "optimization.assumptions": (
            "Gateway alternatives, outcomes, fees, latency, incidents, and capacity "
            "are controlled simulation assumptions—not measurements of real processors."
        ),
        "optimization.timeline": (
            "The routing evaluation uses a synthetic timeline; source transaction "
            "timestamps remain unchanged and separate."
        ),
        "optimization.run_source": "Run ID: {run_id}. Source: {source}.",
        "optimization.input_digest": "Input digest: {digest}",
        "optimization.title": "Payment routing optimization",
        "optimization.summary": (
            "**Optimizer expected utility:** {utility:,.1f}  |  "
            "**Realized success:** {success:.1%}  |  "
            "**Random realized success:** {random:.1%}"
        ),
        "optimization.constraints": (
            "**Binding-capacity buckets:** {binding}  |  "
            "**Infeasible buckets:** {infeasible}  |  "
            "**Unassigned transactions:** {unassigned}"
        ),
        "optimization.greedy_advantage": (
            "**MILP expected-utility advantage over greedy:** {advantage:,.1f}"
        ),
        "optimization.change_title": "Change from baselines",
        "optimization.period_title": "Normal and degraded-period evidence",
        "optimization.utilization_title": "Optimizer gateway utilization",
        "optimization.cumulative_title": "Chronological cumulative utility",
        "optimization.examples_title": "Example optimizer decisions",
        "optimization.uncertainty_title": "Realized-utility uncertainty",
        "optimization.sensitivity_title": "Within-simulator sensitivity evidence",
        "optimization.outcome_sensitivity": "Outcome redraw sensitivity",
        "optimization.allocation_sensitivity": "Probability rerouting sensitivity",
        "optimization.sensitivity_caption": (
            "Seed and ±3-point probability stress tests measure robustness only "
            "inside the hand-authored simulator; they are not real gateway evidence."
        ),
        "optimization.objective": (
            "Objective: {success:g}×success probability − {fee:g}×fee − "
            "{latency:g}×latency. Version: {version}."
        ),
        "optimization.test_period": (
            "Test period: {start} through {end} (complete UTC buckets)."
        ),
        "optimization.uncertainty_caption": (
            "95% intervals use a paired circular moving-block bootstrap over "
            "chronological test buckets. Missing policy buckets are aligned to zero."
        ),
        "optimization.no_intervals": (
            "Realized comparisons require uncertainty intervals before use."
        ),
        "optimization.policy.uniform_random": "Uniform random",
        "optimization.policy.round_robin": "Round robin",
        "optimization.policy.best_static": "Best static gateway",
        "optimization.policy.greedy_utility": "Greedy utility",
        "optimization.policy.milp_optimizer": "Constrained MILP optimizer",
        "optimization.column.policy": "Policy",
        "optimization.column.sample_size": "Sample size",
        "optimization.column.success_rate": "Success rate",
        "optimization.column.total_fee": "Total fee",
        "optimization.column.average_latency": "Average latency (ms)",
        "optimization.column.expected_utility": "Expected utility",
        "optimization.column.baseline": "Baseline",
        "optimization.column.estimate": "Estimate",
        "optimization.column.lower": "Lower 95%",
        "optimization.column.upper": "Upper 95%",
        "optimization.column.includes_zero": "Includes zero",
        "optimization.column.normal_success": "Normal success rate",
        "optimization.column.degraded_success": "Degraded success rate",
        "optimization.column.degraded_transactions": "Degraded transactions",
        "optimization.column.feasible_buckets": "Feasible buckets",
        "optimization.column.infeasible_buckets": "Infeasible buckets",
        "admin.title": "Administrator transaction manager",
        "admin.fallback_disabled": (
            "Database editing is unavailable while demo fallback data is active."
        ),
        "admin.email": "Administrator email",
        "admin.password": "Password",
        "admin.login": "Sign in",
        "admin.logout": "Sign out",
        "admin.not_authorized": "This account is not an approved administrator.",
        "admin.login_failed": "Incorrect administrator password.",
        "admin.signed_in": "Signed in as {email}",
        "admin.add": "Add",
        "admin.edit": "Edit",
        "admin.delete": "Soft delete",
        "admin.choose": "Choose a transaction",
        "admin.save": "Save transaction",
        "admin.update": "Update transaction",
        "admin.confirm_delete": (
            "I confirm this transaction should be hidden from analytics."
        ),
        "admin.confirm_required": "Confirm the soft deletion first.",
        "admin.created": "Transaction created.",
        "admin.updated": "Transaction updated.",
        "admin.deleted": "Transaction soft-deleted.",
        "admin.no_transactions_edit": "No transactions are available to edit.",
        "admin.no_transactions_delete": "No transactions are available to delete.",
        "test.fallback": "Fallback",
    },
    "my": {
        "language.label": "ဘာသာစကား",
        "language.english": "English",
        "language.burmese": "မြန်မာ",
        "language.control_label": "Language / ဘာသာစကား",
        "language.current": "လက်ရှိ: {name}",
        "dashboard.title": "ငွေပေးချေမှု အောင်မြင်နှုန်း စောင့်ကြည့်စနစ်",
        "dashboard.description": (
            "ငွေပေးချေမှု အခြေအနေကို စောင့်ကြည့်ပြီး gateway များကို နှိုင်းယှဉ်ကာ "
            "ပျက်ကွက်မှုများကို dashboard တစ်ခုတည်းမှ စစ်ဆေးပါ။"
        ),
        "dashboard.disclaimer": (
            "ပညာရေးသရုပ်ပြ · Gateway သတ်မှတ်မှုများနှင့် ငွေပေးချေမှုရလဒ်များသည် "
            "ထိန်းချုပ်ဖန်တီးထားသော အတုဒေတာများဖြစ်ပြီး အမှန်တကယ် ဘဏ် သို့မဟုတ် "
            "gateway စွမ်းဆောင်ရည်ကို ကိုယ်စားမပြုပါ။"
        ),
        "shell.product_name": "ငွေပေးချေမှု ကွပ်ကဲရေးစင်တာ",
        "shell.navigation": "ကွပ်ကဲရေးစင်တာ လမ်းညွှန်",
        "shell.view.overview": "အနှစ်ချုပ်",
        "shell.view.gateways": "Gateway အခြေအနေ",
        "shell.view.routing": "လမ်းကြောင်းရွေးချယ်မှု",
        "shell.view.transactions": "ငွေပေးချေမှုများ",
        "shell.view.admin": "စီမံခန့်ခွဲမှု",
        "shell.reset_filters": "စစ်ထုတ်မှုများ ပြန်လည်သတ်မှတ်ရန်",
        "shell.view_description.overview": "လက်ရှိ ငွေပေးချေမှု အခြေအနေကို တစ်ချက်ကြည့်ပါ။",
        "shell.view_description.gateways": "Gateway စွမ်းဆောင်ရည်နှင့် သတိပေးချက်များကို နှိုင်းယှဉ်ပါ။",
        "shell.view_description.routing": "ငွေပေးချေမှု လမ်းကြောင်းရွေးချယ်မှုကို အကောင်းဆုံးပြုလုပ်ပါ။",
        "shell.view_description.transactions": (
            "စစ်ထုတ်ထားသော ငွေပေးချေမှု လုပ်ဆောင်ချက်များကို စစ်ဆေးပါ။"
        ),
        "shell.view_description.admin": "ဒက်ရှ်ဘုတ် ဝင်ရောက်ခွင့်နှင့် ငွေပေးချေမှုများကို စီမံပါ။",
        "sidebar.controls": "Dashboard ထိန်းချုပ်မှုများ",
        "sidebar.replay_description": (
            "ငွေပေးချေမှုမှတ်တမ်းကို အချိန်စဉ်အတိုင်း ကြည့်ရှုပြီး မြင်ကွင်းခွဲခြမ်းမှုကို စစ်ထုတ်ပါ။"
        ),
        "sidebar.replayed_transactions": "မှတ်တမ်းရှိ ငွေပေးချေမှုများ",
        "sidebar.replay_help": "CSV မြင်ကွင်းဟောင်းတွင် အသုံးပြုမည့် မှတ်တမ်းနမူနာကို ထိန်းချုပ်သည်။",
        "sidebar.replay_count": "ငွေပေးချေမှု {total_count:,} ခုအနက် {replay_count:,} ခု",
        "sidebar.display_filters": "ပြသမှု စစ်ထုတ်မှုများ",
        "sidebar.gateway": "Gateway",
        "sidebar.all_gateways": "Gateway အားလုံး",
        "sidebar.transaction_type": "ငွေပေးချေမှု အမျိုးအစား",
        "sidebar.all_transaction_types": "ငွေပေးချေမှု အမျိုးအစားအားလုံး",
        "sidebar.device": "အသုံးပြုသည့် စက်",
        "sidebar.all_devices": "စက်အားလုံး",
        "sidebar.status": "အခြေအနေ",
        "sidebar.all_statuses": "အခြေအနေအားလုံး",
        "sidebar.date_range": "ရက်စွဲအပိုင်းအခြား",
        "sidebar.filter_note": (
            "စစ်ထုတ်မှုများသည် ဇယားများနှင့် KPI များကို ပြောင်းလဲသည်။ သတိပေးချက် "
            "တွက်ချက်မှုများသည် အသုံးပြုနေသော ငွေပေးချေမှုမှတ်တမ်း အပြည့်အစုံကို အမြဲအသုံးပြုသည်။"
        ),
        "kpi.transactions": "ငွေပေးချေမှုများ",
        "kpi.success_rate": "အောင်မြင်နှုန်း",
        "kpi.failed": "မအောင်မြင်သော",
        "kpi.average_latency": "ပျမ်းမျှ ကြာချိန်",
        "kpi.active_alerts": "လက်ရှိ သတိပေးချက်များ",
        "hero.eyebrow": "ငွေပေးချေမှု အခြေအနေ",
        "hero.title": "ငွေပေးချေမှု {successful:,} ခု အောင်မြင်ခဲ့သည် ✦",
        "hero.subtitle": (
            "အောင်မြင်နှုန်း {success_rate:.1%} · ပျမ်းမျှ တုံ့ပြန်ချိန် {average_latency_ms:.1f} ms"
        ),
        "hero.database_live": "MongoDB မှ တိုက်ရိုက်ဒေတာ",
        "hero.demo_mode": "သရုပ်ပြဒေတာ",
        "actions.reset_filters": "စစ်ထုတ်မှုများ ပြန်လည်သတ်မှတ်ရန်",
        "empty.title": "ကိုက်ညီသော ငွေပေးချေမှု မရှိပါ",
        "empty.body": "ငွေပေးချေမှုများကို မြင်ရန် စစ်ထုတ်မှုတစ်ခု သို့မဟုတ် အချို့ကို ပြန်လည်သတ်မှတ်ပါ။",
        "ai.title": "AI လုပ်ငန်းဆောင်ရွက်မှု အနှစ်ချုပ်",
        "ai.description": (
            "MiMo 2.5 Pro ဖြင့် တိုတောင်းသော အနှစ်ချုပ်ကို ဖန်တီးပါ။ "
            "စုစုပေါင်း dashboard ကိန်းဂဏန်းများကိုသာ မျှဝေသည်။"
        ),
        "ai.generate": "AI အနှစ်ချုပ် ဖန်တီးရန်",
        "ai.generating": "AI အနှစ်ချုပ် ဖန်တီးနေသည်...",
        "ai.summary": "အနှစ်ချုပ်",
        "ai.risks": "အန္တရာယ်များ",
        "ai.actions": "လုပ်ဆောင်ချက်များ",
        "ai.evidence": "အထောက်အထား",
        "ai.origin.ai": "AI ဖြင့် ဖန်တီးထားသည်",
        "ai.origin.local": "စက်တွင်း၌ ဖန်တီးထားသည် (AI မရရှိနိုင်ပါ)",
        "ai.requires_data": ("အနှစ်ချုပ် မဖန်တီးမီ ငွေပေးချေမှုများ ပြန်ပေးသည့် စစ်ထုတ်မှုများကို ရွေးပါ။"),
        "ai.invalid_response": "AI အနှစ်ချုပ်ကို မဖန်တီးနိုင်ပါ။ ထပ်မံကြိုးစားပါ။",
        "database.fallback_not_configured": (
            "ဒေတာဘေ့စ်ကို သတ်မှတ်မထားသဖြင့် သရုပ်ပြဒေတာကို ပြသထားသည်။"
        ),
        "database.fallback_unavailable": (
            "ဒေတာဘေ့စ်ကို ယာယီ အသုံးမပြုနိုင်သဖြင့် သရုပ်ပြဒေတာကို ပြသထားသည်။"
        ),
        "source.live_label": "MongoDB မှ တိုက်ရိုက်ဒေတာ",
        "source.demo_label": "သရုပ်ပြဖန်တီးထားသော ဒေတာ",
        "source.simulation_disclosure": (
            "Simulation {version}: Gateway သတ်မှတ်မှုများနှင့် dashboard ရလဒ်များသည် "
            "ဤပညာရေးသရုပ်ပြအတွက် ထိန်းချုပ်ဖန်တီးထားသော အတုဒေတာများဖြစ်သည်။"
        ),
        "source.degraded_warning": (
            "MongoDB ကို အသုံးမပြုနိုင်ပါ။ သရုပ်ပြဖန်တီးထားသော ဒေတာကို အသုံးပြုနေပြီး "
            "ပြင်ဆင်မှုများကို ပိတ်ထားသည်။"
        ),
        "source.diagnostics": "ဒေတာဘေ့စ် အခြေအနေနှင့် ပြန်လည်ရယူမှု",
        "source.diagnostic_category": "စစ်ဆေးချက် အမျိုးအစား: {category}",
        "source.retry_guidance": ("MongoDB သတ်မှတ်ချက် သို့မဟုတ် ချိတ်ဆက်မှုကို စစ်ဆေးပြီး ထပ်မံကြိုးစားပါ။"),
        "source.retry": "MongoDB ကို ထပ်မံကြိုးစားရန်",
        "pagination.page": "ငွေပေးချေမှု စာမျက်နှာ",
        "pagination.previous": "ယခင်စာမျက်နှာ",
        "pagination.next": "နောက်စာမျက်နှာ",
        "pagination.summary": ("စာမျက်နှာ {page}/{pages} · ငွေပေးချေမှု {total:,} ခု"),
        "health.title": "Gateway အခြေအနေ",
        "health.description": (
            "Gateway တစ်ခု၏ နောက်ဆုံး ငွေပေးချေမှု ၅၀ ခုသည် dataset တစ်ခုလုံး၏ "
            "အခြေခံနှုန်းထက် အနည်းဆုံး ရာခိုင်နှုန်း ၁၀ မှတ် လျော့နည်းလျှင် သတိပေးချက် ပေါ်သည်။"
        ),
        "health.no_alert": "Gateway တစ်ခုမျှ ၁၀ မှတ် သတိပေးချက် သတ်မှတ်ချက်ကို မကျော်လွန်ပါ။",
        "health.action_required": "ဆောင်ရွက်ရန်လိုအပ်သည်- {names} တွင် အောင်မြင်နှုန်း လျော့ကျမှု တွေ့ရှိသည်။",
        "health.insufficient_history": "မှတ်တမ်းမလုံလောက်ပါ",
        "health.alert": "သတိပေးချက်",
        "health.healthy": "ကောင်းမွန်",
        "health.baseline": "အခြေခံနှုန်း",
        "health.latest_50": "နောက်ဆုံး ၅၀",
        "health.drop": "လျော့ကျမှု",
        "health.samples": "နမူနာ (အခြေခံ/လတ်တလော)",
        "health.periods": "နှိုင်းယှဉ်ကာလ (UTC)",
        "health.interval": "လျော့ကျမှု ၉၅% interval",
        "charts.gateway_performance": "Gateway စွမ်းဆောင်ရည်",
        "charts.success_rate_by_gateway": "ဂိတ်ဝေးအလိုက် အောင်မြင်နှုန်း",
        "charts.transaction_volume_by_gateway": "ဂိတ်ဝေးအလိုက် ငွေပေးချေမှုပမာဏ",
        "charts.success_trend": "အောင်မြင်နှုန်း လမ်းကြောင်း",
        "charts.failures_by": "{title} အလိုက် မအောင်မြင်မှုများ",
        "dimensions.gateway": "ဂိတ်ဝေး",
        "dimensions.timestamp": "အချိန်မှတ်တမ်း",
        "dimensions.fraud_flag": "လိမ်လည်မှု အမှတ်အသား",
        "dimensions.latency_band": "တုံ့ပြန်ချိန် အပိုင်းအခြား",
        "dimensions.device": "အသုံးပြုသည့် စက်",
        "dimensions.transaction_type": "ငွေပေးချေမှု အမျိုးအစား",
        "sections.failure_analysis": "မအောင်မြင်မှု ခွဲခြမ်းစိတ်ဖြာခြင်း",
        "sections.failure_analysis_description": (
            "ထပ်တလဲလဲ ဖြစ်ပေါ်နေသော ပုံစံများကို ရှာဖွေရန် မအောင်မြင်သော ငွေပေးချေမှုများကို ခွဲခြမ်းပါ။"
        ),
        "table.gateway": "ဂိတ်ဝေး",
        "table.transaction_id": "ငွေပေးချေမှု ID",
        "table.timestamp": "အချိန်မှတ်တမ်း",
        "table.transaction_type": "ငွေပေးချေမှု အမျိုးအစား",
        "table.transaction_status": "ငွေပေးချေမှု အခြေအနေ",
        "table.transaction_amount": "ငွေပမာဏ",
        "table.device_used": "အသုံးပြုသည့် စက်",
        "table.latency_ms": "တုံ့ပြန်ချိန် (ms)",
        "table.fraud_flag": "လိမ်လည်မှု အမှတ်အသား",
        "table.recent_transactions": "နောက်ဆုံး ငွေပေးချေမှုများ",
        "guide.title": "ဤ dashboard ကို နားလည်ရန်",
        "guide.content": (
            "- **အခြေခံနှုန်း** သည် နောက်ဆုံး ၅၀ window မတိုင်မီ active history ရှိ "
            "gateway တစ်ခုစီ၏ အောင်မြင်နှုန်းဖြစ်သည်။\n"
            "- **နောက်ဆုံး ၅၀** သည် အသုံးပြုနေသော မှတ်တမ်းထဲမှ နောက်ဆုံး ငွေပေးချေမှု ၅၀ ခု၏ "
            "အောင်မြင်နှုန်းဖြစ်သည်။\n"
            "- **လျော့ကျမှု** သည် အခြေခံနှုန်းမှ နောက်ဆုံး ၅၀ ၏ စွမ်းဆောင်ရည်ကို နုတ်ထားခြင်းဖြစ်သည်။\n"
            "- Gateway သတ်မှတ်မှုနှင့် ရလဒ်များကို ထိန်းချုပ်ဖန်တီးထားသောကြောင့် "
            "နှိုင်းယှဉ်မှုများသည် သရုပ်ပြရန်သာဖြစ်သည်။"
        ),
        "errors.no_matching_transactions": (
            "ရွေးချယ်ထားသော စစ်ထုတ်မှုများနှင့် ကိုက်ညီသော ငွေပေးချေမှုမရှိပါ။ ဆက်လက်ရန် "
            "ဘေးဘားစစ်ထုတ်မှုတစ်ခု သို့မဟုတ် တစ်ခုထက်ပို၍ ရှင်းလင်းပါ။"
        ),
        "errors.load_data": "Dashboard data ကို မဖွင့်နိုင်ပါ: {exc}",
        "errors.prepare_data_guidance": (
            "`python -m payment_dashboard.prepare_data` ဖြင့် ပြင်ဆင်ထားသော dataset ကို "
            "ဖန်တီးပြီး ဤစာမျက်နှာကို ပြန်လည်ဖွင့်ပါ။"
        ),
        "optimization.eyebrow": "ဖန်တီးထားသော စမ်းသပ် benchmark",
        "optimization.assumptions": (
            "Gateway ရွေးချယ်မှု၊ ရလဒ်၊ ကုန်ကျစရိတ်၊ တုံ့ပြန်ချိန်၊ incident နှင့် "
            "capacity များသည် ထိန်းချုပ်ဖန်တီးထားသော ယူဆချက်များသာဖြစ်သည်။"
        ),
        "optimization.timeline": (
            "Routing အကဲဖြတ်မှုသည် ဖန်တီးထားသော အချိန်စဉ်ကို အသုံးပြုပြီး "
            "မူရင်း transaction အချိန်များကို မပြောင်းလဲပါ။"
        ),
        "optimization.run_source": "Run ID: {run_id}။ ဒေတာရင်းမြစ်: {source}။",
        "optimization.input_digest": "ထည့်သွင်းဒေတာ digest: {digest}",
        "optimization.title": "ငွေပေးချေမှု routing အကောင်းဆုံးဖြစ်စေရေး",
        "optimization.summary": (
            "**Optimizer မျှော်မှန်း utility:** {utility:,.1f}  |  "
            "**လက်တွေ့အောင်မြင်နှုန်း:** {success:.1%}  |  "
            "**ကျပန်းမူ အောင်မြင်နှုန်း:** {random:.1%}"
        ),
        "optimization.constraints": (
            "**Capacity ပြည့်သည့် bucket:** {binding}  |  "
            "**မဖြေရှင်းနိုင်သည့် bucket:** {infeasible}  |  "
            "**မသတ်မှတ်နိုင်သည့် transaction:** {unassigned}"
        ),
        "optimization.greedy_advantage": (
            "**Greedy ထက် MILP ၏ မျှော်မှန်း utility အားသာချက်:** {advantage:,.1f}"
        ),
        "optimization.change_title": "အခြေခံ policy များနှင့် ကွာခြားမှု",
        "optimization.period_title": "ပုံမှန်နှင့် ချို့ယွင်းကာလ အထောက်အထား",
        "optimization.utilization_title": "Optimizer gateway အသုံးချမှု",
        "optimization.cumulative_title": "အချိန်စဉ်အလိုက် စုစုပေါင်း utility",
        "optimization.examples_title": "Optimizer ဆုံးဖြတ်ချက် နမူနာများ",
        "optimization.uncertainty_title": "လက်တွေ့ utility မသေချာမှု",
        "optimization.sensitivity_title": "Simulator အတွင်း sensitivity အထောက်အထား",
        "optimization.outcome_sensitivity": "Outcome ပြန်လည် draw sensitivity",
        "optimization.allocation_sensitivity": (
            "Probability ပြောင်းလဲ rerouting sensitivity"
        ),
        "optimization.sensitivity_caption": (
            "Seed နှင့် probability ±3-point stress test များသည် ဖန်တီးထားသော "
            "simulator အတွင်း ခိုင်မာမှုကိုသာ တိုင်းတာပြီး gateway အစစ်အမှန် အထောက်အထား မဟုတ်ပါ။"
        ),
        "optimization.objective": (
            "ရည်မှန်းချက်: {success:g}×အောင်မြင်နိုင်ခြေ − {fee:g}×ကုန်ကျစရိတ် − "
            "{latency:g}×တုံ့ပြန်ချိန်။ Version: {version}။"
        ),
        "optimization.test_period": "စမ်းသပ်ကာလ: {start} မှ {end} အထိ (UTC bucket အပြည့်)။",
        "optimization.uncertainty_caption": (
            "95% interval များကို အချိန်စဉ် bucket များအပေါ် paired circular "
            "moving-block bootstrap ဖြင့်တွက်ထားပြီး ပျောက်နေသော bucket ကို သုညထားသည်။"
        ),
        "optimization.no_intervals": "လက်တွေ့နှိုင်းယှဉ်မှုအတွက် uncertainty interval လိုအပ်သည်။",
        "optimization.policy.uniform_random": "ကျပန်းတူညီ ရွေးချယ်မှု",
        "optimization.policy.round_robin": "အစဉ်လိုက် လှည့်ပတ်ရွေးချယ်မှု",
        "optimization.policy.best_static": "အကောင်းဆုံး တစ်သတ်မှတ် gateway",
        "optimization.policy.greedy_utility": "Greedy utility",
        "optimization.policy.milp_optimizer": "ကန့်သတ်ချက်ပါ MILP optimizer",
        "optimization.column.policy": "မူဝါဒ",
        "optimization.column.sample_size": "နမူနာအရေအတွက်",
        "optimization.column.success_rate": "အောင်မြင်နှုန်း",
        "optimization.column.total_fee": "စုစုပေါင်း ကုန်ကျစရိတ်",
        "optimization.column.average_latency": "ပျမ်းမျှ တုံ့ပြန်ချိန် (ms)",
        "optimization.column.expected_utility": "မျှော်မှန်း utility",
        "optimization.column.baseline": "အခြေခံ policy",
        "optimization.column.estimate": "ခန့်မှန်းတန်ဖိုး",
        "optimization.column.lower": "အောက်ခြေ 95%",
        "optimization.column.upper": "အပေါ်ခြေ 95%",
        "optimization.column.includes_zero": "သုည ပါဝင်မှု",
        "optimization.column.normal_success": "ပုံမှန်ကာလ အောင်မြင်နှုန်း",
        "optimization.column.degraded_success": "ချို့ယွင်းကာလ အောင်မြင်နှုန်း",
        "optimization.column.degraded_transactions": "ချို့ယွင်းကာလ transaction",
        "optimization.column.feasible_buckets": "ဖြေရှင်းနိုင်သည့် bucket",
        "optimization.column.infeasible_buckets": "မဖြေရှင်းနိုင်သည့် bucket",
        "admin.title": "စီမံခန့်ခွဲသူ ငွေပေးချေမှု စီမံခန့်ခွဲမှု",
        "admin.fallback_disabled": (
            "Demo fallback data အသုံးပြုနေချိန် database ပြင်ဆင်မှု မရနိုင်ပါ။"
        ),
        "admin.email": "စီမံခန့်ခွဲသူ အီးမေးလ်",
        "admin.password": "စကားဝှက်",
        "admin.login": "ဝင်ရောက်ရန်",
        "admin.logout": "ထွက်ရန်",
        "admin.not_authorized": "ဤအကောင့်သည် ခွင့်ပြုထားသော စီမံခန့်ခွဲသူ မဟုတ်ပါ။",
        "admin.login_failed": "စီမံခန့်ခွဲသူ စကားဝှက် မမှန်ပါ။",
        "admin.signed_in": "{email} ဖြင့် ဝင်ရောက်ထားသည်",
        "admin.add": "အသစ်ထည့်ရန်",
        "admin.edit": "ပြင်ဆင်ရန်",
        "admin.delete": "ဖျက်ထားကြောင်း မှတ်ရန်",
        "admin.choose": "ငွေပေးချေမှု ရွေးရန်",
        "admin.save": "ငွေပေးချေမှု သိမ်းရန်",
        "admin.update": "ငွေပေးချေမှု ပြင်ဆင်ရန်",
        "admin.confirm_delete": "ဤငွေပေးချေမှုကို ခွဲခြမ်းမှုမှ ဖျောက်ရန် အတည်ပြုသည်။",
        "admin.confirm_required": "Soft deletion ကို ဦးစွာ အတည်ပြုပါ။",
        "admin.created": "ငွေပေးချေမှု အသစ်ထည့်ပြီးပါပြီ။",
        "admin.updated": "ငွေပေးချေမှု ပြင်ဆင်ပြီးပါပြီ။",
        "admin.deleted": "ငွေပေးချေမှုကို soft-delete ပြုလုပ်ပြီးပါပြီ။",
        "admin.no_transactions_edit": "ပြင်ဆင်ရန် ငွေပေးချေမှု မရှိပါ။",
        "admin.no_transactions_delete": "ဖျက်ရန် ငွေပေးချေမှု မရှိပါ။",
        "test.fallback": "",
    },
}


def translate(key: str, language: str = DEFAULT_LANGUAGE, **values: object) -> str:
    """Return a localized string, falling back to English for missing values."""
    english = TRANSLATIONS["en"].get(key, key)
    localized = TRANSLATIONS.get(language, TRANSLATIONS["en"]).get(key, english)
    template = localized or english
    return template.format(**values)
